version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: sharingan
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  postgres-test:
    image: postgres
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: sharingan-test
      PGPORT: 5434
    ports:
      - '5434:5434'
  redis:
    image: redis:latest
    ports:
      - '6379:6379' # Map host port 6379 to container port 6379
    volumes:
      - redis_data:/data # Persistent volume for Redis

volumes:
  postgres-data:
  redis_data:
